### PR TITLE
feat: code refactoring and fix some issues

### LINKED ISSUE #5: Module breaks the search results page
Hello!

Using this module on a Hyva project (Default un-modified Hyva theme):

smile/elasticsuite: 2.11.1.1
hyva-themes/magento2-smile-elasticsuite: 1.2.0
hyva-themes/magento2-default-theme: 1.2.3

But the **search results** page breaks with the following error:

Error: Call to a member function setUniqueId() on bool in /vendor/shellpea/magento-advanced-elasticsuite-catalog/view/frontend/templates/catalog/layer/filter/attribute.phtml:16

This seems to be happening because in:
- In vendor/shellpea/magento-advanced-elasticsuite-catalog/view/frontend/layout/hyva_catalogsearch_result_index.xml the "attribute-filter-js" block is removed

Screenshot 2023-05-25 at 11 34 58

- In vendor/shellpea/magento-advanced-elasticsuite-catalog/view/frontend/templates/catalog/layer/filter/attribute.phtml the "attribute-filter-js" block is being loaded.

Screenshot 2023-05-25 at 11 35 09

Is this intended or am I missing something?

Thank you!

### PR DESCRIPTION
**Pull request by AlexDroomer**
### AdvancedElasticSuiteCatalog v.1.2.1

- Performed logic refactoring
- Fixed the search page logic #5
- Added coding standard improvements
- Added clearUrl logic for the search page

### CODE REVIEW

File: Block/ListProduct.php [hunk 1]
```diff
@@ -13,9 +14,43 @@
...
 use Magento\Framework\Registry;
 use Magento\Catalog\Model\CategoryFactory;
+use Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\CollectionFactory;
 
 class ListProduct extends \Magento\Catalog\Block\Product\ListProduct
 {
+    /**
+     * @var ScopeConfigInterface
+     */
+    private $scopeConfig;
```
Comment (vsushkov) [inline Block/ListProduct.php]: Please, change all `private` methods and attributes to `protected`, so in case when someone want's to override something in the module, they'll be able to change anything

File: Model/AjaxResponse.php [hunk 2]
```diff
@@ -208,9 +206,9 @@ protected function getFilterItems(): array
                 $items[$datascope] = [];
                 $attribute = $filter->getAttributeModel();
                 foreach ($filter->getItems() as $item) {
-                    if($this->swatchHelper->isSwatchAttribute($attribute)) {
+                    if ($this->swatchHelper->isSwatchAttribute($attribute)) {
```
Comment (vsushkov) [inline Model/AjaxResponse.php]: The call to `isSwatchAttribute` will be made multiple times, because it's with the `foreach ($filter->getItems() as $items)` loop.
I would suggest to pull up this `if` statement, so you check if it's a swatch attribute only once per each filter, and not multiple times per each filter (meaning, one time per each filter item).

Maybe something like that:

```php

              $attribute = $filter->getAttributeModel();
              if ($this->swatchHelper->isSwatchAttribute($attribute)) {
                  foreach ($filter->getItems() as $item) {
                      // prepare the swatch'ed item
                  }
              } else {
                  foreach ($filter->getItems() as $item) {
                        $items[$datascope][] = $item->toArray(['label', 'count', 'url', 'is_selected']);
                  }
              }

```

File: Model/AjaxResponse.php [hunk 3]
```diff
@@ -208,9 +206,9 @@ protected function getFilterItems(): array
                 $items[$datascope] = [];
```
Comment (vsushkov) [inline Model/AjaxResponse.php:205]: Instead of `is_a` it's better to use `instanceof`, as it works faster:
```php
if ($filter instanceof Attribute::class) {
```

File: Block/AdvancedCatalog.php [hunk 4]
```diff
@@ -195,25 +196,26 @@ protected function getUnusedOption(FilterItem $filterItem)
     /**
      * Get filter items
      *
-     * @return string[]
+     * @return array
      */
     protected function getFilterItems(): array
     {
-        /** @var Navigation $navBlock */
         $navBlock = $this->getNavBlock();
```
Comment (vsushkov) [inline Block/AdvancedCatalog.php]: I suggest to replace everything below this line in this method with a call to `\Shellpea\AdvancedElasticsuiteCatalog\Model\AjaxResponse::getFilterItems()`. Something like this:

```php
    public function __construct(
        \Shellpea\AdvancedElasticsuiteCatalog\Model\AjaxResponseFactory $ajaxResponseFactory
    ) {
        $this->ajaxResponseFactory = $ajaxResponseFactory;
    }

    protected function getFilterItems(): array
    {
        $ajaxResponse = $this->ajaxResponseFactory->create();
        $ajaxResponse->getFilterItems($this->getNavBlock());
    }

```

File: view/frontend/layout/hyva_catalogsearch_result_index.xml [hunk 5]
```diff
@@ -31,12 +31,12 @@
...
             <referenceBlock name="catalogsearch.leftnav"
                    template="Shellpea_AdvancedElasticsuiteCatalog::catalog/layer/view.phtml">
-                <referenceBlock name="catalogsearch.navigation.state" />
+                <referenceBlock name="catalogsearch.navigation.state" template="Shellpea_AdvancedElasticsuiteCatalog::catalog/layer/state.phtml" />
                 <referenceBlock name="catalogsearch.navigation.renderer">
 
                     <referenceBlock name="catalogsearch.navigation.renderer.attribute"
                         template="Shellpea_AdvancedElasticsuiteCatalog::catalog/layer/filter/attribute.phtml">
-                        <referenceBlock name="attribute-filter-js" remove="true"/>
+                        <referenceBlock name="attribute-filter-js"/>
```
Comment (vsushkov) [inline view/frontend/layout/hyva_catalogsearch_result_index.xml:39]: As we're not doing anything to the attribute-filter-js block, let's remove this line from the layout

```suggestion
```

**Review by vsushkov — CHANGES_REQUESTED** [review]

File: view/frontend/layout/hyva_catalogsearch_result_index.xml (hunk 5 above)
Comment (AlexDroomer) [reply view/frontend/layout/hyva_catalogsearch_result_index.xml:39]: One of the reasons why there was a problem on the search page is that this block is needed in the current version of the module😉

**Review by vsushkov — APPROVED** [review]
